update

diff --git a/.github/workflows/repo.yaml b/.github/workflows/repo.yaml
--- a/.github/workflows/repo.yaml
+++ b/.github/workflows/repo.yaml
@@ -69,30 +69,30 @@ jobs:
             ls -l
             pacman -U --noconfirm aurutils-*.pkg.*
 
-            # 配置本地仓库
-            echo "[${REPO_IDENTIFIER}]" >> /etc/pacman.conf
-            echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf
-            echo "Server = file://${GITHUB_WORKSPACE} " >> /etc/pacman.conf
-            # mkdir -p /home/auruser/${GITHUB_WORKSPACE}
-            repo-add ${GITHUB_WORKSPACE}/${REPO_IDENTIFIER}.db.tar.gz ${GITHUB_WORKSPACE}/aurutils-*.pkg.*
+            # # 配置本地仓库
+            # echo "[${REPO_IDENTIFIER}]" >> /etc/pacman.conf
+            # echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf
+            # echo "Server = file://${GITHUB_WORKSPACE} " >> /etc/pacman.conf
+            # # mkdir -p /home/auruser/${GITHUB_WORKSPACE}
+            # repo-add ${GITHUB_WORKSPACE}/${REPO_IDENTIFIER}.db.tar.gz ${GITHUB_WORKSPACE}/aurutils-*.pkg.*
 
-            # # 修改文件权限以允许auruser访问
-            # chown auruser:auruser ${GITHUB_WORKSPACE}
-            pacman -Sy --noconfirm
+            # # # 修改文件权限以允许auruser访问
+            # # chown auruser:auruser ${GITHUB_WORKSPACE}
+            # pacman -Sy --noconfirm
 
-            # 拉取需要构建的自定义Arch软件包
-            cd ${GITHUB_WORKSPACE}
-            chmod u+w ${GITHUB_WORKSPACE}
-            sudo -u auruser sh fetch-pkgs.sh
+            # # 拉取需要构建的自定义Arch软件包
+            # cd ${GITHUB_WORKSPACE}
+            # chmod u+w ${GITHUB_WORKSPACE}
+            # sudo -u auruser sh fetch-pkgs.sh
 
-            # 构建自定义软件包
-            cd $PKGS_DIR
-            for pkgdir in *; do
-              echo $pkgdir
-              # if [ -d "$pkgdir" ]; then
-              #     sudo -u auruser aur sync --sign -A --noconfirm --noview --database ${REPO_IDENTIFIER} --root ${GITHUB_WORKSPACE} ${pkg} || echo "!!! Package ${pkg} failed"
-              # fi
-            done
+            # # 构建自定义软件包
+            # cd $PKGS_DIR
+            # for pkgdir in *; do
+            #   echo $pkgdir
+            #   # if [ -d "$pkgdir" ]; then
+            #   #     sudo -u auruser aur sync --sign -A --noconfirm --noview --database ${REPO_IDENTIFIER} --root ${GITHUB_WORKSPACE} ${pkg} || echo "!!! Package ${pkg} failed"
+            #   # fi
+            # done
 
       - name: Remove symbolic links
         run: |
